backend:
  name: github
  repo: kmukawa0126/kmukawa-website
  branch: main
  base_url: https://frolicking-bublanina-a90bb7.netlify.app
  auth_endpoint: api/auth

media_folder: "images/blog"
public_folder: "/images/blog"

locale: ja

collections:
  - name: "blog"
    label: "ブログ記事"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "投稿日", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image", required: false }
      - { label: "本文", name: "body", widget: "markdown" }
